version: "3"
services:
  web:
    image: noefc/client
    ports:
      - 80:80
    restart_policy:
      condition: on-failure
    networks:
      - prod
  api:
    image: noefc/api
    network_mode: "host"
    networks:
      - prod
    volumes:
     - /src/config:./apiconfig
networks:
  prod: