version: "3"
services:
  web:
    image: noefc/client
    network_mode: "host"
    ports:
      - 80:80
  api:
    image: noefc/api
    network_mode: "host"
    volumes:
     - ./apiconfig:/src/config