version: "3"
services:
  proxy:
    image: jwilder/nginx-proxy
    depends_on:
      - app
      - api
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
  app:
    image: noefc/client
    environment:
      - VIRTUAL_HOST=www.cerberus-noe.fr, cerberus-noe.fr
  api:
    image: noefc/api
    links:
      - db
    volumes:
      - ./apiconfig:/app/src/config
    environment:
      - VIRTUAL_HOST=api.cerberus-noe.fr
      - WAIT_HOSTS=db:3306
  db:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=noe
    volumes:
      - /var/noe/mysql:/var/lib/mysql
