version: "3"
services:
  proxy:
    image: jwilder/nginx-proxy
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
  app:
    image: noefc/client
    networks:
      - frontend
    environment:
      - VIRTUAL_HOST=www.cerberus-noe.fr, cerberus-noe.fr
  api:
    image: noefc/api
    ports:
      - 80:3000
    networks:
      - frontend
      - backend
    volumes:
      - ./apiconfig:/src/config
    environment:
      - VIRTUAL_HOST=api.cerberus-noe.fr
  db:
    image: mariadb
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=noe
    volumes:
      - /var/lib/mysql:/var/lib/mysql
networks:
  frontend:
  backend: